name: Web Scraper

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 8am UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
          opam-repositories: |
            default: https://opam.ocaml.org
          opam-depext: false  # Disable automatic system dependency installation
      
      - name: Install system dependencies manually
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap g++-multilib gcc-multilib mercurial musl-tools rsync
      
      - name: Install OCaml dependencies
        run: |
          opam install . --deps-only --with-test
      
      - name: Build and run scraper
        run: |
          eval $(opam env)
          dune build
          dune exec -- src/main.exe
