name: NBA Game Recomender Emailer

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 8am UTC every day
  workflow_dispatch:     # Allows manual triggering from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-22.04
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
      
      - name: Install dependencies
        run: |
          opam install . --deps-only
          opam install dune
      
      - name: Build and run scraper
        run: |
          eval $(opam env)
          dune build
          dune exec -- src/main.exe