name: NBA Emailer

on:
  schedule:
    - cron: '0 3 * * *'  # Runs at 8am UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-22.04
    env:
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          if [ -f dune-project ]; then
            echo "dune-project found"
            cat dune-project
          else
            echo "dune-project not found"
          fi
      
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.0
          cache-prefix: v1-${{ hashFiles('**/*.opam') }}-${{ hashFiles('**/dune-project') }}
      
      - name: Install OCaml dependencies
        run: |
          opam install . --deps-only
          opam install cohttp-lwt-unix yojson lwt tls-lwt lambdasoup uri dotenv base --yes
          opam install dune
          eval $(opam env)
          dune build --display=short
      
      - name: Run Program
        run: |
          eval $(opam env)
          dune exec -- src/main.exe